on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build-matrix:
    name: Release Rust Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_target: [aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install Rust target for ARM64
        run: rustup target add ${{ matrix.rust_target }}

      - name: Build Rust Binary
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          cargo build --release --target ${{ matrix.rust_target }}

      - name: Archive the binary
        run: |
          mkdir release
          cp target/${{ matrix.rust_target }}/release/your_project_name release/your_project_name-${{ matrix.rust_target }}-${{ env.VERSION }}
          tar -czvf release/your_project_name-${{ matrix.rust_target }}-${{ env.VERSION }}.tar.gz release/your_project_name-${{ matrix.rust_target }}-${{ env.VERSION }}
        env:
          VERSION: ${{ env.VERSION }}

      - name: Create GitHub Release with binary
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
